name: Pipeline Calculadora PHP

on:
  push:
    branches: [main]

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer

      - name: Instalar dependências do Composer
        run: composer install --no-interaction --prefer-dist

      - name: Executar teste soma
        run: ./vendor/bin/phpunit test_soma.php