name: Pipeline Calculadora PHP

on:
  push:
    branches: [main]

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer

      - name: Verificar PHP
        run: php --version

      - name: Verificar Composer
        run: composer --version

      - name: Instalar dependências
        run: composer install --no-interaction --prefer-dist

      - name: Verificar PHPUnit
        run: php vendor/bin/phpunit --version

      - name: Executar teste soma
        run: php vendor/bin/phpunit test_soma.php

      - name: Executar teste menos
        run: php vendor/bin/phpunit test_menos.php

      - name: Executar teste multiplicação
        run: php vendor/bin/phpunit test_multiplicacao.php

      - name: Executar teste divisão
        run: php vendor/bin/phpunit test_divisao.php