on:
  push:
    branches: [main]

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - name: Instalar PHPUnit
        run: composer install

      - name: Executar teste soma
        run: ./vendor/bin/phpunit test_soma.php